### ISSUE TITLE
Not all tiktok tracking domains are blocked.

### ISSUE THREAD

**Issue by Clyde6790pGIT** [mrxehmad/pi-hole-adlist#2]
![image](https://github.com/user-attachments/assets/a3770682-059e-45c6-ac45-8207051982ae)
The domains with a check mark near them means they are blocked.

**Comment by mrxehmad** [comment]
Tiktok ha endless domains tbh. list has to be updated daily.
best way is to use regext filter
`^(.+\.)??(abtest-sg-tiktok.byteoversea|abtest-va-tiktok.byteoversea|gts.byteoversea|isnssdk|lf1-ttcdn-tos.pstatp|muscdn|musemuse|musical|p1-tt-ipv6.byteimg|p16-tiktok-sg.ibyteimg|p16-tiktok-sign-va-h2.ibyteimg|p16-tiktok-va-h2.ibyteimg|p16-tiktok-va.ibyteimg|p16-va-tiktok.ibyteimg|p26-tt.byteimg|p3-tt-ipv6.byteimg|p9-tt.byteimg|pull-f3-hs.pstatp|pull-f5-hs.flive.pstatp|pull-f5-hs.pstatp|pull-f5-mus.pstatp|pull-flv-f1-hs.pstatp|pull-flv-f6-hs.pstatp|pull-flv-l1-hs.pstatp|pull-flv-l1-mus.pstatp|pull-flv-l6-hs.pstatp|pull-hls-l1-mus.pstatp|pull-l3-hs.pstatp|pull-rtmp-f1-hs.pstatp|pull-rtmp-f6-hs.pstatp|pull-rtmp-l1-hs.pstatp|pull-rtmp-l1-mus.pstatp|pull-rtmp-l6-hs.pstatp|quic-tiktok-core-proxy-i18n-gcpva.byteoversea|quic-tiktok-proxy-i18n-gcpva.byteoversea|sf1-ttcdn-tos.pstatp|sf16-ttcdn-tos.ipstatp|sf6-ttcdn-tos.pstatp|sgsnssdk|tiktok-lb-alisg.byteoversea|tiktok-lb-maliva.byteoversea|tiktok-platform-lb-alisg.byteoversea|tiktok|tiktokcdn-in|tiktokcdn-us|tiktokcdn-us.com.atomile|tiktokcdn|tiktokcdn.com.atomile|tiktokcdn.com.c.bytetcdn|tiktokcdn.com.c.worldfcdn|tiktokcdn.com.rocket-cdn|tiktokd|tiktokv|tiktokv.com.c.worldcdn|tiktokv.com.c.worldfcdn2|tlivecdn|ttlivecdn|ttlivecdn.com.c.worldcdn|ttoverseaus|ttoversea|byteoversea)\.(com|co|org|it|ca|cn|ly|net|au|ai|net|jp|us|tv|cc)$
`
this works for me

**Comment by Clyde6790pGIT** [comment]
> Tiktok ha endless domains tbh. list has to be updated daily. best way is to use regext filter `^(.+\.)??(abtest-sg-tiktok.byteoversea|abtest-va-tiktok.byteoversea|gts.byteoversea|isnssdk|lf1-ttcdn-tos.pstatp|muscdn|musemuse|musical|p1-tt-ipv6.byteimg|p16-tiktok-sg.ibyteimg|p16-tiktok-sign-va-h2.ibyteimg|p16-tiktok-va-h2.ibyteimg|p16-tiktok-va.ibyteimg|p16-va-tiktok.ibyteimg|p26-tt.byteimg|p3-tt-ipv6.byteimg|p9-tt.byteimg|pull-f3-hs.pstatp|pull-f5-hs.flive.pstatp|pull-f5-hs.pstatp|pull-f5-mus.pstatp|pull-flv-f1-hs.pstatp|pull-flv-f6-hs.pstatp|pull-flv-l1-hs.pstatp|pull-flv-l1-mus.pstatp|pull-flv-l6-hs.pstatp|pull-hls-l1-mus.pstatp|pull-l3-hs.pstatp|pull-rtmp-f1-hs.pstatp|pull-rtmp-f6-hs.pstatp|pull-rtmp-l1-hs.pstatp|pull-rtmp-l1-mus.pstatp|pull-rtmp-l6-hs.pstatp|quic-tiktok-core-proxy-i18n-gcpva.byteoversea|quic-tiktok-proxy-i18n-gcpva.byteoversea|sf1-ttcdn-tos.pstatp|sf16-ttcdn-tos.ipstatp|sf6-ttcdn-tos.pstatp|sgsnssdk|tiktok-lb-alisg.byteoversea|tiktok-lb-maliva.byteoversea|tiktok-platform-lb-alisg.byteoversea|tiktok|tiktokcdn-in|tiktokcdn-us|tiktokcdn-us.com.atomile|tiktokcdn|tiktokcdn.com.atomile|tiktokcdn.com.c.bytetcdn|tiktokcdn.com.c.worldfcdn|tiktokcdn.com.rocket-cdn|tiktokd|tiktokv|tiktokv.com.c.worldcdn|tiktokv.com.c.worldfcdn2|tlivecdn|ttlivecdn|ttlivecdn.com.c.worldcdn|ttoverseaus|ttoversea|byteoversea)\.(com|co|org|it|ca|cn|ly|net|au|ai|net|jp|us|tv|cc)$ ` this works for me

Thanks, this made it pass tiktok tracker blocking.
